/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MiCuentaRouteImport } from './routes/mi-cuenta'
import { Route as RestablecerClaveRouteImport } from './routes/restablecer-clave'
import { Route as MayoristasRouteImport } from './routes/mayoristas'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as ProductosSlugRouteImport } from './routes/productos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MiCuentaRoute = MiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerClaveRoute = RestablecerClaveRouteImport.update({
  id: '/restablecer-clave',
  path: '/restablecer-clave',
  getParentRoute: () => rootRouteImport,
} as any)
const MayoristasRoute = MayoristasRouteImport.update({
  id: '/mayoristas',
  path: '/mayoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosSlugRoute = ProductosSlugRouteImport.update({
  id: '/productos/$slug',
  path: '/productos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/restablecer-clave': typeof RestablecerClaveRoute
  '/mayoristas': typeof MayoristasRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/restablecer-clave': typeof RestablecerClaveRoute
  '/mayoristas': typeof MayoristasRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/productos': typeof ProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/restablecer-clave': typeof RestablecerClaveRoute
  '/mayoristas': typeof MayoristasRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/admin' | '/mi-cuenta' | '/restablecer-clave' | '/mayoristas' | '/productos/$slug' | '/productos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/admin' | '/mi-cuenta' | '/restablecer-clave' | '/mayoristas' | '/productos/$slug' | '/productos'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin'
    | '/mi-cuenta'
    | '/restablecer-clave'
    | '/mayoristas'
    | '/productos/$slug'
    | '/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminRoute: typeof AdminRoute
  MiCuentaRoute: typeof MiCuentaRoute
  RestablecerClaveRoute: typeof RestablecerClaveRoute
  MayoristasRoute: typeof MayoristasRoute
  ProductosSlugRoute: typeof ProductosSlugRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-cuenta': {
      id: '/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof MiCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer-clave': {
      id: '/restablecer-clave'
      path: '/restablecer-clave'
      fullPath: '/restablecer-clave'
      preLoaderRoute: typeof RestablecerClaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mayoristas': {
      id: '/mayoristas'
      path: '/mayoristas'
      fullPath: '/mayoristas'
      preLoaderRoute: typeof MayoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$slug': {
      id: '/productos/$slug'
      path: '/productos/$slug'
      fullPath: '/productos/$slug'
      preLoaderRoute: typeof ProductosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminRoute: AdminRoute,
  MiCuentaRoute: MiCuentaRoute,
  RestablecerClaveRoute: RestablecerClaveRoute,
  MayoristasRoute: MayoristasRoute,
  ProductosSlugRoute: ProductosSlugRoute,
  ProductosIndexRoute: ProductosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
